### ISSUE TITLE
Using Diplomat in database.yml on Rails

### ISSUE THREAD

**Issue by danhart** [phusion/passenger#2009]
I'm attempting to use https://github.com/WeAreFarmGeek/diplomat

As per their README instructions I have adjusted my database.yml like so:
```yaml
<% if Rails.env.production? %>
production:
  adapter:            postgresql
  encoding:           unicode
  host:               <%= Diplomat::Service.get('postgres').Address %>
  database:           <%= Diplomat::Kv.get('project/db/name') %>
  pool:               5
  username:           <%= Diplomat::Kv.get('project/db/user') %>
  password:           <%= Diplomat::Kv.get('project/db/pass') %>
  port:               <%= Diplomat::Service.get('postgres').ServicePort %>
<% end %>
```

When running with `RAILS_ENV=production rails c`, I can connect to the database fine. However, when the app is started with passenger, it seems these values are blank and I get the error:
```
ActionView::Template::Error (No connection pool with 'primary' found.)
```

I assume that passenger is being clever with the database.yml?

My suspicion is that ERB templating for the database.yml does not really
work except for with ENV vars explicitly passed from the nginx configuration.
