### ISSUE TITLE
redmine production and development in multiple instance

### ISSUE THREAD

**Issue by ashrafalzyoud** [phusion/passenger#2309]
database.yml
```
production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  pool: 10
 
development:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  pool: 10
```
my nginx
```
server {
        listen 80;
        server_name www.ashrafalzyod.com;

        error_log /var/log/nginx/ashrafalzyoud.error.log;
        access_log /var/log/nginx/ashrafalzyoud.access.log;

        root /home/redmine/4.11/public;

        passenger_enabled on;
        passenger_app_env development;
        passenger_app_group_name ashrafalzyoud;
        passenger_min_instances 3;
        passenger_friendly_error_pages on;
        passenger_ruby /home/redmine/.rbenv/versions/2.6.6/bin/ruby;
        client_max_body_size    10m;
}
server {
        listen 80;
        server_name www.ashrafalzyod.com;
        root /home/redmine/4.11/public;

         passenger_enabled on;
         passenger_app_env production;

        passenger_app_group_name ashrafalzyoud;
        passenger_friendly_error_pages on;
        passenger_ruby /home/redmine/.rbenv/versions/2.6.6/bin/ruby;
        client_max_body_size    10m;
}
passenger_pre_start http://www.ashrafalzyoud.com/;
```
passenger-status
```
redmine@172:~/4.11$ passenger-status 
*** Cleaning stale instance directory /tmp/passenger.UjIOTlH
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.UjIOTlH/.
It appears that multiple Phusion Passenger instances are running. Please
select a specific one by running:

  passenger-status <NAME>

The following Phusion Passenger instances are running:

Name                       PID      Description
--------------------------------------------------------------------------
oR2Fxrti                   41650    nginx/1.18.0 Phusion_Passenger/6.0.6
XBKtMEPL                   89988    nginx/1.18.0 Phusion_Passenger/6.0.6

```

its normal to be in multiple instance or no??
